export default async function handler(req, res) {
  const { prompt } = req.body;

  // demo response (later AI API जोड़ेंगे)
  const result = `
Website Idea:
${prompt}

<!DOCTYPE html>
<html>
<head><title>Generated Site</title></head>
<body>
<h1>${prompt}</h1>
</body>
</html>
`;

  res.status(200).json({ result });
}
export default async function handler(req, res) {
  const { prompt } = req.body;

  const code = `
<!DOCTYPE html>
<html>
<head>
  <title>Generated Site</title>
  <style>
    body { font-family: Arial; text-align:center; padding:40px; }
    h1 { color: blue; }
  </style>
</head>
<body>

  <h1>${prompt}</h1>
  <p>This website is generated by AI Website Builder V2</p>

</body>
</html>
`;

  res.status(200).json({ code });
}
