export default async function handler(req, res) {
  const { prompt } = req.body;

  // demo response (later AI API जोड़ेंगे)
  const result = `
Website Idea:
${prompt}

<!DOCTYPE html>
<html>
<head><title>Generated Site</title></head>
<body>
<h1>${prompt}</h1>
</body>
</html>
`;

  res.status(200).json({ result });
}
export default async function handler(req, res) {

  if (req.method !== "POST") {
    return res.status(405).json({
      error: "Method Not Allowed"
    });
  }

  const { prompt } = req.body;

  if (!prompt) {
    return res.status(400).json({
      error: "Prompt is required"
    });
  }

  // Demo HTML (अभी Groq API नहीं जोड़ा गया है)
  const html = `
<!DOCTYPE html>
<html>
<head>
<title>Generated Website</title>
<style>
body{
font-family:Arial,sans-serif;
text-align:center;
padding:50px;
background:#f4f4f4;
}
h1{
color:#2563eb;
}
</style>
</head>
<body>

<h1>${prompt}</h1>

<p>🚀 This website was generated by Reyansh AI Builder.</p>

</body>
</html>
`;

  return res.status(200).json({
    code: html
  });
}
